#!/usr/bin/env bash
# Stamps a new standards-compliant backend module under
# internal/modules/<name>, following the medicore/pharmacy shape:
# forced-RLS migration with a status CHECK, respond-helper routes
# (create -> Accepted, list -> OK, guarded transition -> 404/409),
# a published event constant, a consumer stub satisfying the arch-test
# naming rules, and a module_test.go built on testutil.NewHarness.
#
# Usage: ./scripts/new-module.sh <name>   (run from backend/)
set -euo pipefail

NAME="${1:?usage: new-module.sh <name>}"
[[ "$NAME" =~ ^[a-z]+$ ]] || { echo "name must be lowercase letters only (a-z)"; exit 1; }

case "$NAME" in
  package|select|type|func|range|map|chan|go|if|else|for|return|var|const|import|interface|struct|switch|defer|break|continue|fallthrough|goto|default)
    echo "name must not be a Go keyword: $NAME"
    exit 1
    ;;
esac

DIR="internal/modules/$NAME"
[[ -e "$DIR" ]] && { echo "module $NAME already exists"; exit 1; }
mkdir -p "$DIR/contract"

cat > "$DIR/contract/events.go" <<'EOF'
// Package contract is __NAME__'s published event interface. Data only:
// consts, types and vars, importing nothing beyond time and uuid. See
// docs/standards/backend.md and internal/archtest/contract_test.go.
package contract

// SubjectItemCreated is published when an item is created.
const SubjectItemCreated = "hms.in.__NAME__.item_created.v1"

// SubjectItemDone is published when an item transitions to done.
const SubjectItemDone = "hms.in.__NAME__.item_done.v1"

// ItemCreatedData is the v1 payload of SubjectItemCreated.
type ItemCreatedData struct {
	ItemID string `json:"item_id"`
	Name   string `json:"name"`
}

// ItemDoneData is the v1 payload of SubjectItemDone.
type ItemDoneData struct {
	ItemID string `json:"item_id"`
}
EOF

cat > "$DIR/module.go" <<'EOF'
// Package __NAME__ owns __NAME__ items. Generated by new-module.sh from
// the medicore/pharmacy template — rename the placeholder "item" domain
// nouns to your real ones before shipping.
package __NAME__

import (
	"context"
	"encoding/json"
	"errors"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/google/uuid"
	"gorm.io/gorm"

	__NAME__contract "github.com/tesserix/helivanta/internal/modules/__NAME__/contract"
	"github.com/tesserix/helivanta/internal/platform"
	"github.com/tesserix/helivanta/internal/platform/respond"
	"github.com/tesserix/helivanta/pkg/authn"
	"github.com/tesserix/helivanta/pkg/authz"
	"github.com/tesserix/helivanta/pkg/events"
	"github.com/tesserix/helivanta/pkg/pagination"
	"github.com/tesserix/helivanta/pkg/tenantdb"
)

// TODO: rename these permissions to your real domain nouns before
// shipping ("<module>.<resource>.<action>", see
// docs/standards/backend.md section 11).
const (
	PermItemRead  authz.Permission = "__NAME__.item.read"
	PermItemWrite authz.Permission = "__NAME__.item.write"
)

type Module struct{}

func New() *Module { return &Module{} }

func (m *Module) Name() string { return "__NAME__" }

func (m *Module) Permissions() []authz.Grant {
	return []authz.Grant{
		{Permission: PermItemRead, Roles: []authz.Role{}},   // TODO: choose the roles that hold this permission
		{Permission: PermItemWrite, Roles: []authz.Role{}},  // TODO: choose the roles that hold this permission
	}
}

func (m *Module) Migrations() []tenantdb.Migration {
	return []tenantdb.Migration{{
		ID: "0001___NAME__",
		SQL: `
			CREATE TABLE __NAME___items (
			  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
			  tenant_id uuid NOT NULL,
			  name text NOT NULL,
			  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','done')),
			  done_at timestamptz,
			  created_at timestamptz NOT NULL DEFAULT now()
			);
			ALTER TABLE __NAME___items ENABLE ROW LEVEL SECURITY;
			ALTER TABLE __NAME___items FORCE ROW LEVEL SECURITY;
			-- Calling hms_tenant_visible directly here (no two-step ALTER
			-- POLICY, unlike medicore/pharmacy/lab/iam) is safe only because
			-- the platform migration defining it always runs first; those
			-- modules' tables predate the function and needed a follow-up step.
			CREATE POLICY tenant_isolation ON __NAME___items
			  USING (hms_tenant_visible(tenant_id))
			  WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
			CREATE INDEX ON __NAME___items (tenant_id, created_at DESC);`,
	}}
}

type item struct {
	ID        uuid.UUID  `gorm:"type:uuid;default:gen_random_uuid()" json:"id"`
	TenantID  uuid.UUID  `json:"-"`
	Name      string     `json:"name"`
	Status    string     `gorm:"default:pending" json:"status"`
	DoneAt    *time.Time `json:"done_at"`
	CreatedAt time.Time  `json:"created_at"`
}

func (item) TableName() string { return "__NAME___items" }

// PageKey is the keyset position of this row, satisfying platform.Keyed.
func (i item) PageKey() (time.Time, uuid.UUID) { return i.CreatedAt, i.ID }

type createItemRequest struct {
	Name string `json:"name" binding:"required,max=200"`
}

// listItems returns one page of this tenant's items, newest first.
//
// It returns whatever ApplyKeyset yields — up to Limit+1 rows — and does
// not trim, does not decide has_more and does not build a cursor.
// platform.ListRoute owns all three, so they cannot be got wrong per
// endpoint.
func listItems(deps platform.Deps) platform.ListHandler[item] {
	return func(c *gin.Context, p pagination.Params) ([]item, error) {
		principal, _, ok := authn.TenantPrincipal(c)
		if !ok {
			return nil, nil
		}
		var rows []item
		err := deps.DB.WithTenant(c.Request.Context(), principal.TenantID, func(tx *gorm.DB) error {
			return tenantdb.ApplyKeyset(tx, p).Find(&rows).Error
		})
		return rows, err
	}
}

func (m *Module) Routes(r *platform.Router, deps platform.Deps) {
	g := r.Group("/__NAME__")

	g.POST("/items", PermItemWrite, func(c *gin.Context) {
		p, tenantUUID, ok := authn.TenantPrincipal(c)
		if !ok {
			return
		}
		var req createItemRequest
		if err := c.ShouldBindJSON(&req); err != nil {
			respond.BadRequest(c, err)
			return
		}
		row := item{TenantID: tenantUUID, Name: req.Name}
		err := deps.DB.WithTenant(c.Request.Context(), p.TenantID, func(tx *gorm.DB) error {
			if err := tx.Create(&row).Error; err != nil {
				return err
			}
			data, err := json.Marshal(__NAME__contract.ItemCreatedData{ItemID: row.ID.String(), Name: row.Name})
			if err != nil {
				return err
			}
			return deps.Bus.Publish(tx, __NAME__contract.SubjectItemCreated, events.Event{
				Type: "ItemCreated", Version: 1, TenantID: p.TenantID, Data: data,
			})
		})
		if err != nil {
			respond.InternalErr(c, err, "could not create item")
			return
		}
		respond.Accepted(c, gin.H{"id": row.ID.String()})
	})

	platform.ListRoute(g, "/items", PermItemRead, listItems(deps))

	g.POST("/items/:id/done", PermItemWrite, func(c *gin.Context) {
		p, _, ok := authn.TenantPrincipal(c)
		if !ok {
			return
		}
		id, err := uuid.Parse(c.Param("id"))
		if err != nil {
			respond.NotFound(c, "item")
			return
		}
		var status int
		err = deps.DB.WithTenant(c.Request.Context(), p.TenantID, func(tx *gorm.DB) error {
			var row item
			if err := tx.First(&row, "id = ?", id).Error; err != nil {
				return err
			}
			if row.Status != "pending" {
				status = http.StatusConflict
				return nil
			}
			now := time.Now().UTC()
			result := tx.Model(&item{}).Where("id = ? AND status = 'pending'", id).
				Updates(map[string]any{"status": "done", "done_at": now})
			if result.Error != nil {
				return result.Error
			}
			if result.RowsAffected == 0 {
				// Lost the race to a concurrent transition between the
				// pre-check above and this guarded UPDATE.
				status = http.StatusConflict
				return nil
			}
			data, err := json.Marshal(__NAME__contract.ItemDoneData{ItemID: row.ID.String()})
			if err != nil {
				return err
			}
			return deps.Bus.Publish(tx, __NAME__contract.SubjectItemDone, events.Event{
				Type: "ItemDone", Version: 1, TenantID: p.TenantID, Data: data,
			})
		})
		if errors.Is(err, gorm.ErrRecordNotFound) {
			respond.NotFound(c, "item")
			return
		}
		if err != nil {
			respond.InternalErr(c, err, "could not complete item")
			return
		}
		if status == http.StatusConflict {
			respond.Conflict(c, "already done")
			return
		}
		respond.OK(c, gin.H{"id": id.String(), "status": "done"})
	})
}

// Publishes declares every subject this module publishes, using
// constants from its own contract package —
// TestPublishesUsesContractConstants requires it.
func (m *Module) Publishes() []string {
	return []string{__NAME__contract.SubjectItemCreated, __NAME__contract.SubjectItemDone}
}

func (m *Module) Consumers(deps platform.Deps) []events.Consumer {
	return []events.Consumer{{
		Name:    "__NAME__-intake",
		Subject: __NAME__contract.SubjectItemCreated,
		Handle: func(ctx context.Context, tx *gorm.DB, evt events.Event) error {
			// TODO: replace this stub. Point Subject at the upstream
			// module's published event and handle it here (see
			// pharmacy's visit-intake consumer for the pattern). Left as
			// a self-subscription to this module's own item_created so
			// the generated module compiles, satisfies the consumer
			// naming contract, and passes
			// TestConsumersUnmarshalIntoContractTypes out of the box —
			// unmarshal into __NAME__contract.ItemCreatedData, not a
			// local copy.
			var d __NAME__contract.ItemCreatedData
			return json.Unmarshal(evt.Data, &d)
		},
	}}
}

// Broadcasts declares none: __NAME__ has no per-replica cache to
// invalidate. See platform.Module.Broadcasts's doc comment (iam's
// revocation-cache invalidation is the one module that needs this).
func (m *Module) Broadcasts(platform.Deps) []events.Broadcast { return nil }
EOF

cat > "$DIR/module_test.go" <<'EOF'
package __NAME___test

import (
	"context"
	"encoding/json"
	"net/http"
	"sync"
	"testing"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/stretchr/testify/require"
	"gorm.io/gorm"

	"github.com/tesserix/helivanta/internal/modules/__NAME__" //nolint:depguard // external test package importing the module under test (self-import), not cross-module coupling
	"github.com/tesserix/helivanta/internal/platform"
	"github.com/tesserix/helivanta/internal/testutil"
	"github.com/tesserix/helivanta/pkg/authz"
	"github.com/tesserix/helivanta/pkg/tenantdb"
)

var do = testutil.Do

func setup(t *testing.T) (*gin.Engine, *tenantdb.DB, context.Context) {
	r, db, _, ctx := testutil.NewHarness(t, testutil.HarnessOptions{
		Tokens: map[string]string{"tokA": testutil.TenantA, "tokB": testutil.TenantB},
		Perms: map[string][]authz.Permission{
			"tokA": {__NAME__.PermItemRead, __NAME__.PermItemWrite},
			"tokB": {__NAME__.PermItemRead, __NAME__.PermItemWrite},
		},
		Modules: []platform.Module{__NAME__.New()},
	})
	return r, db, ctx
}

func TestItemsCreateListIsolation(t *testing.T) {
	r, _, _ := setup(t)

	require.Equal(t, http.StatusAccepted,
		do(r, "POST", "/v1/__NAME__/items", "tokA", `{"name":"First item"}`).Code)
	require.Equal(t, http.StatusBadRequest,
		do(r, "POST", "/v1/__NAME__/items", "tokA", `{}`).Code)
	require.Contains(t, do(r, "GET", "/v1/__NAME__/items", "tokA", "").Body.String(), "First item")
	require.NotContains(t, do(r, "GET", "/v1/__NAME__/items", "tokB", "").Body.String(), "First item")
}

func TestItemDoneTransition(t *testing.T) {
	r, db, ctx := setup(t)

	require.Equal(t, http.StatusAccepted,
		do(r, "POST", "/v1/__NAME__/items", "tokA", `{"name":"Second item"}`).Code)

	var itemID string
	require.Eventually(t, func() bool {
		var resp struct {
			Data []struct {
				ID string `json:"id"`
			} `json:"data"`
		}
		_ = json.Unmarshal(do(r, "GET", "/v1/__NAME__/items", "tokA", "").Body.Bytes(), &resp)
		if len(resp.Data) == 0 {
			return false
		}
		itemID = resp.Data[0].ID
		return true
	}, 20*time.Second, 200*time.Millisecond)

	// Cross-tenant transition probe → 404.
	require.Equal(t, http.StatusNotFound,
		do(r, "POST", "/v1/__NAME__/items/"+itemID+"/done", "tokB", "").Code)

	// Transition succeeds once…
	require.Equal(t, http.StatusOK,
		do(r, "POST", "/v1/__NAME__/items/"+itemID+"/done", "tokA", "").Code)
	require.Contains(t, do(r, "GET", "/v1/__NAME__/items", "tokA", "").Body.String(), `"done"`)

	// …and 409s on repeat.
	require.Equal(t, http.StatusConflict,
		do(r, "POST", "/v1/__NAME__/items/"+itemID+"/done", "tokA", "").Code)

	// item_created hit the outbox.
	require.Eventually(t, func() bool {
		var n int64
		_ = db.WithSystem(ctx, func(tx *gorm.DB) error {
			return tx.Raw(`SELECT count(*) FROM outbox_events
				WHERE subject = 'hms.in.__NAME__.item_created.v1'`).Scan(&n).Error
		})
		return n == 1
	}, 10*time.Second, 200*time.Millisecond)
}

// Exactly one of N concurrent transitions may win. The guarded UPDATE is
// what enforces it — under READ COMMITTED the losers re-evaluate
// "WHERE status = 'pending'" after the winner commits and match zero
// rows. Delete that branch and this test fails; the sequential flow test
// does not, because it never reaches the UPDATE.
func TestConcurrentDoneYieldsExactlyOneWinner(t *testing.T) {
	r, _, _ := setup(t)

	require.Equal(t, http.StatusAccepted,
		do(r, "POST", "/v1/__NAME__/items", "tokA", `{"name":"Concurrent item"}`).Code)

	var itemID string
	require.Eventually(t, func() bool {
		var resp struct {
			Data []struct {
				ID string `json:"id"`
			} `json:"data"`
		}
		_ = json.Unmarshal(do(r, "GET", "/v1/__NAME__/items", "tokA", "").Body.Bytes(), &resp)
		if len(resp.Data) == 0 {
			return false
		}
		itemID = resp.Data[0].ID
		return true
	}, 20*time.Second, 200*time.Millisecond)

	const n = 8
	codes := make(chan int, n)
	var start sync.WaitGroup
	start.Add(1)
	for i := 0; i < n; i++ {
		go func() {
			start.Wait()
			codes <- do(r, "POST", "/v1/__NAME__/items/"+itemID+"/done", "tokA", "").Code
		}()
	}
	start.Done()

	ok, conflict, other := 0, 0, 0
	for i := 0; i < n; i++ {
		switch c := <-codes; c {
		case http.StatusOK:
			ok++
		case http.StatusConflict:
			conflict++
		default:
			other++
			t.Logf("unexpected status %d", c)
		}
	}
	require.Equal(t, 1, ok, "exactly one transition must win")
	require.Equal(t, n-1, conflict, "every loser must get 409")
	require.Zero(t, other)
}
EOF

# Substitute the module name placeholder now that the heredocs (quoted,
# so backticks in the Go/SQL templates above were not shell-expanded)
# are on disk.
sed -i.bak "s/__NAME__/$NAME/g" "$DIR/module.go" "$DIR/module_test.go" "$DIR/contract/events.go"
rm -f "$DIR/module.go.bak" "$DIR/module_test.go.bak" "$DIR/contract/events.go.bak"

gofmt -w "$DIR"

echo "Created $DIR. Follow-ups:"
echo "1. Register ${NAME}.New() in internal/bootstrap/modules.go's Modules() (shared by cmd/api and cmd/migrate)"
echo "2. Add ${NAME}.New() to allModules() in internal/archtest/arch_test.go"
echo "3. Add \"github.com/tesserix/helivanta/internal/modules/$NAME/contract\" to the module-isolation allow list in backend/.golangci.yml — depguard's allow list names each contract package explicitly, so lint fails on the first cross-module import of yours until it's added"
echo "4. Declare real permissions and the roles that hold them in Permissions() (docs/standards/backend.md section 11)"
echo "5. Add those permissions/roles to approvedPermissionMatrix in internal/archtest/matrix_test.go"
echo "6. Rename the placeholder 'item' domain to your real nouns"
echo "7. cd backend && go test -race ./internal/modules/$NAME/ ./internal/archtest/"
