#!/usr/bin/env bash
# Stamps a new standards-compliant backend module under
# internal/modules/<name>, following the medicore/pharmacy shape:
# forced-RLS migration with a status CHECK, respond-helper routes
# (create -> Accepted, list -> OK, guarded transition -> 404/409),
# a published event constant, a consumer stub satisfying the arch-test
# naming rules, and a module_test.go built on testutil.ModuleHarness.
#
# Usage: ./scripts/new-module.sh <name>   (run from backend/)
set -euo pipefail

NAME="${1:?usage: new-module.sh <name>}"
[[ "$NAME" =~ ^[a-z][a-z0-9]*$ ]] || { echo "name must be lowercase alphanumeric, starting with a letter"; exit 1; }

DIR="internal/modules/$NAME"
[[ -e "$DIR" ]] && { echo "module $NAME already exists"; exit 1; }
mkdir -p "$DIR"

cat > "$DIR/module.go" <<'EOF'
// Package __NAME__ owns __NAME__ items. Generated by new-module.sh from
// the medicore/pharmacy template — rename the placeholder "item" domain
// nouns to your real ones before shipping.
package __NAME__

import (
	"context"
	"encoding/json"
	"errors"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/google/uuid"
	"gorm.io/gorm"

	"github.com/tesserix/hms/internal/platform"
	"github.com/tesserix/hms/internal/platform/respond"
	"github.com/tesserix/hms/pkg/authn"
	"github.com/tesserix/hms/pkg/events"
	"github.com/tesserix/hms/pkg/tenantdb"
)

const (
	// SubjectItemCreated is published when an item is created.
	SubjectItemCreated = "hms.in.__NAME__.item_created.v1"
	// SubjectItemDone is published when an item transitions to done.
	SubjectItemDone = "hms.in.__NAME__.item_done.v1"
)

type Module struct{}

func New() *Module { return &Module{} }

func (m *Module) Name() string { return "__NAME__" }

func (m *Module) Migrations() []tenantdb.Migration {
	return []tenantdb.Migration{{
		ID: "0001___NAME__",
		SQL: `
			CREATE TABLE __NAME___items (
			  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
			  tenant_id uuid NOT NULL,
			  name text NOT NULL,
			  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','done')),
			  done_at timestamptz,
			  created_at timestamptz NOT NULL DEFAULT now()
			);
			ALTER TABLE __NAME___items ENABLE ROW LEVEL SECURITY;
			ALTER TABLE __NAME___items FORCE ROW LEVEL SECURITY;
			CREATE POLICY tenant_isolation ON __NAME___items
			  USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
			  WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
			CREATE INDEX ON __NAME___items (tenant_id, created_at DESC);`,
	}}
}

type item struct {
	ID        uuid.UUID  `gorm:"type:uuid;default:gen_random_uuid()" json:"id"`
	TenantID  uuid.UUID  `json:"-"`
	Name      string     `json:"name"`
	Status    string     `gorm:"default:pending" json:"status"`
	DoneAt    *time.Time `json:"done_at"`
	CreatedAt time.Time  `json:"created_at"`
}

func (item) TableName() string { return "__NAME___items" }

type createItemRequest struct {
	Name string `json:"name" binding:"required,max=200"`
}

// ItemCreatedData is the v1 payload of item_created.
type ItemCreatedData struct {
	ItemID string `json:"item_id"`
	Name   string `json:"name"`
}

type itemDoneData struct {
	ItemID string `json:"item_id"`
}

func (m *Module) Routes(r *gin.RouterGroup, deps platform.Deps) {
	g := r.Group("/__NAME__")

	g.POST("/items", func(c *gin.Context) {
		p, tenantUUID, ok := authn.TenantPrincipal(c)
		if !ok {
			return
		}
		var req createItemRequest
		if err := c.ShouldBindJSON(&req); err != nil {
			respond.BadRequest(c, err)
			return
		}
		row := item{TenantID: tenantUUID, Name: req.Name}
		err := deps.DB.WithTenant(c.Request.Context(), p.TenantID, func(tx *gorm.DB) error {
			if err := tx.Create(&row).Error; err != nil {
				return err
			}
			data, err := json.Marshal(ItemCreatedData{ItemID: row.ID.String(), Name: row.Name})
			if err != nil {
				return err
			}
			return deps.Bus.Publish(tx, SubjectItemCreated, events.Event{
				Type: "ItemCreated", Version: 1, TenantID: p.TenantID, Data: data,
			})
		})
		if err != nil {
			respond.Internal(c, "could not create item")
			return
		}
		respond.Accepted(c, gin.H{"id": row.ID.String()})
	})

	g.GET("/items", func(c *gin.Context) {
		p, _, ok := authn.TenantPrincipal(c)
		if !ok {
			return
		}
		var rows []item
		err := deps.DB.WithTenant(c.Request.Context(), p.TenantID, func(tx *gorm.DB) error {
			return tx.Order("created_at DESC").Limit(100).Find(&rows).Error
		})
		if err != nil {
			respond.Internal(c, "could not list items")
			return
		}
		respond.OK(c, gin.H{"data": rows})
	})

	g.POST("/items/:id/done", func(c *gin.Context) {
		p, _, ok := authn.TenantPrincipal(c)
		if !ok {
			return
		}
		id, err := uuid.Parse(c.Param("id"))
		if err != nil {
			respond.NotFound(c, "item")
			return
		}
		var status int
		err = deps.DB.WithTenant(c.Request.Context(), p.TenantID, func(tx *gorm.DB) error {
			var row item
			if err := tx.First(&row, "id = ?", id).Error; err != nil {
				return err
			}
			if row.Status != "pending" {
				status = http.StatusConflict
				return nil
			}
			now := time.Now().UTC()
			result := tx.Model(&item{}).Where("id = ? AND status = 'pending'", id).
				Updates(map[string]any{"status": "done", "done_at": now})
			if result.Error != nil {
				return result.Error
			}
			if result.RowsAffected == 0 {
				// Lost the race to a concurrent transition between the
				// pre-check above and this guarded UPDATE.
				status = http.StatusConflict
				return nil
			}
			data, err := json.Marshal(itemDoneData{ItemID: row.ID.String()})
			if err != nil {
				return err
			}
			return deps.Bus.Publish(tx, SubjectItemDone, events.Event{
				Type: "ItemDone", Version: 1, TenantID: p.TenantID, Data: data,
			})
		})
		if errors.Is(err, gorm.ErrRecordNotFound) {
			respond.NotFound(c, "item")
			return
		}
		if err != nil {
			respond.Internal(c, "could not complete item")
			return
		}
		if status == http.StatusConflict {
			respond.Conflict(c, "already done")
			return
		}
		respond.OK(c, gin.H{"id": id.String(), "status": "done"})
	})
}

func (m *Module) Consumers(deps platform.Deps) []events.Consumer {
	return []events.Consumer{{
		Name:    "__NAME__-intake",
		Subject: SubjectItemCreated,
		Handle: func(ctx context.Context, tx *gorm.DB, evt events.Event) error {
			// TODO: replace this stub. Point Subject at the upstream
			// module's published event and handle it here (see
			// pharmacy's visit-intake consumer for the pattern). Left as
			// a no-op so the generated module compiles and satisfies the
			// consumer naming contract out of the box.
			return nil
		},
	}}
}
EOF

cat > "$DIR/module_test.go" <<'EOF'
package __NAME___test

import (
	"context"
	"encoding/json"
	"net/http"
	"testing"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/stretchr/testify/require"
	"gorm.io/gorm"

	"github.com/tesserix/hms/internal/modules/__NAME__" //nolint:depguard // external test package importing the module under test (self-import), not cross-module coupling
	"github.com/tesserix/hms/internal/testutil"
	"github.com/tesserix/hms/pkg/tenantdb"
)

var do = testutil.Do

func setup(t *testing.T) (*gin.Engine, *tenantdb.DB, context.Context) {
	r, db, _, ctx := testutil.ModuleHarness(t,
		map[string]string{"tokA": testutil.TenantA, "tokB": testutil.TenantB},
		__NAME__.New())
	return r, db, ctx
}

func TestItemsCreateListIsolation(t *testing.T) {
	r, _, _ := setup(t)

	require.Equal(t, http.StatusAccepted,
		do(r, "POST", "/v1/__NAME__/items", "tokA", `{"name":"First item"}`).Code)
	require.Equal(t, http.StatusBadRequest,
		do(r, "POST", "/v1/__NAME__/items", "tokA", `{}`).Code)
	require.Contains(t, do(r, "GET", "/v1/__NAME__/items", "tokA", "").Body.String(), "First item")
	require.NotContains(t, do(r, "GET", "/v1/__NAME__/items", "tokB", "").Body.String(), "First item")
}

func TestItemDoneTransition(t *testing.T) {
	r, db, ctx := setup(t)

	require.Equal(t, http.StatusAccepted,
		do(r, "POST", "/v1/__NAME__/items", "tokA", `{"name":"Second item"}`).Code)

	var itemID string
	require.Eventually(t, func() bool {
		var resp struct {
			Data []struct {
				ID string `json:"id"`
			} `json:"data"`
		}
		_ = json.Unmarshal(do(r, "GET", "/v1/__NAME__/items", "tokA", "").Body.Bytes(), &resp)
		if len(resp.Data) == 0 {
			return false
		}
		itemID = resp.Data[0].ID
		return true
	}, 20*time.Second, 200*time.Millisecond)

	// Cross-tenant transition probe → 404.
	require.Equal(t, http.StatusNotFound,
		do(r, "POST", "/v1/__NAME__/items/"+itemID+"/done", "tokB", "").Code)

	// Transition succeeds once…
	require.Equal(t, http.StatusOK,
		do(r, "POST", "/v1/__NAME__/items/"+itemID+"/done", "tokA", "").Code)
	require.Contains(t, do(r, "GET", "/v1/__NAME__/items", "tokA", "").Body.String(), `"done"`)

	// …and 409s on repeat.
	require.Equal(t, http.StatusConflict,
		do(r, "POST", "/v1/__NAME__/items/"+itemID+"/done", "tokA", "").Code)

	// item_created hit the outbox.
	require.Eventually(t, func() bool {
		var n int64
		_ = db.WithSystem(ctx, func(tx *gorm.DB) error {
			return tx.Raw(`SELECT count(*) FROM outbox_events
				WHERE subject = 'hms.in.__NAME__.item_created.v1'`).Scan(&n).Error
		})
		return n == 1
	}, 10*time.Second, 200*time.Millisecond)
}
EOF

# Substitute the module name placeholder now that the heredocs (quoted,
# so backticks in the Go/SQL templates above were not shell-expanded)
# are on disk.
sed -i.bak "s/__NAME__/$NAME/g" "$DIR/module.go" "$DIR/module_test.go"
rm -f "$DIR/module.go.bak" "$DIR/module_test.go.bak"

gofmt -w "$DIR"

echo "Created $DIR. Follow-ups:"
echo "1. Register ${NAME}.New() in cmd/api/main.go (registry loop)"
echo "2. Add ${NAME}.New() to allModules() in internal/archtest/arch_test.go"
echo "3. Rename the placeholder 'item' domain to your real nouns"
echo "4. cd backend && go test -race ./internal/modules/$NAME/ ./internal/archtest/"
