-- Runtime role: no superuser, no RLS bypass. Migrations run as `hms`.
CREATE ROLE hms_app LOGIN PASSWORD 'hms_app' NOSUPERUSER NOBYPASSRLS;
GRANT USAGE ON SCHEMA public TO hms_app;
ALTER DEFAULT PRIVILEGES FOR ROLE hms IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO hms_app;
ALTER DEFAULT PRIVILEGES FOR ROLE hms IN SCHEMA public
  GRANT USAGE, SELECT ON SEQUENCES TO hms_app;
